services:

  backend:
    build: ./backend
    container_name: spring_api
    ports:
      - "8080:8080"
    restart: always

  frontend:
    build: ./frontend
    container_name: vue_app
    ports:
      - "5173:80"
    depends_on:
      - backend